//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danisman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Danisman()
        {
            this.IletisimOgrencisiSecilenDanismanIlıskisi = new HashSet<IletisimOgrencisiSecilenDanismanIlıskisi>();
        }
    
        public int danisman_id { get; set; }
        public string danisman_adi { get; set; }
        public string danisman_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IletisimOgrencisiSecilenDanismanIlıskisi> IletisimOgrencisiSecilenDanismanIlıskisi { get; set; }
    }
}
