//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciRezervasyonİliskisi
    {
        public string kullanıcı_rezervasyon_id { get; set; }
        public int kullanici_id { get; set; }
        public int rezervasyon_id { get; set; }
    
        public virtual OgrenciRezervasyonBilgileri OgrenciRezervasyonBilgileri { get; set; }
        public virtual OgrenciRezervasyonDurumu OgrenciRezervasyonDurumu { get; set; }
    }
}
